server:
  port: 8080

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice_db
    username: dat
    password: 13712nct
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html


app:
  jwt:
    secret: myVerySecretKeyThatIsAtLeast32CharactersLong
    expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.example.userservice: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always